### ISSUE TITLE
[BUG]: IPFS will continue & return a success code, despite: no IPFS key being provided, and path being incorrect.

### ISSUE THREAD

**Issue by komaake** [0x0zAgency/infinitymint-beta#68]
## Steps to reproduce:

1. Open a new InfinityMint project from the _react-typescsript_ starterkit.
2. Create a new project from the example with `ipfs: true` in `infinitymint.config.ts`
3. Attempt to compile a project.

## Expected behaviour:

To exit with a status code saying the IPFS key is invalid/not found, and that the path provided for the asset is invalid (Should not return `undefined`.)

![Screenshot 2023-04-20 at 21 45 58](https://user-images.githubusercontent.com/108497196/233483833-70878945-c1c9-48c1-abe7-a5aef9967352.png)

**Comment by llydia-eth** [comment]
This was fixed in the latest version.
